import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["cyrillic"],
});

export const unifraktur = localFont({
  src: [
    {
      path: "./fonts/UnifrakturMaguntia-Book.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-unifractur",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${unifraktur.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
